name: Deploy to BunnyCDN

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build SvelteKit
        run: npm run build

      - name: Upload to BunnyCDN
        uses: ayeressian/bunnycdn-storage-deploy@v2.2.5
        with:
          source: "build"
          storageEndpoint: "${{ secrets.STORAGE_ENDPOINT }}"
          storageZoneName: "${{ secrets.STORAGE_NAME }}"
          storagePassword: "${{ secrets.STORAGE_PASSWORD }}"
          accessKey: "${{ secrets.STORAGE_KEY }}"
          pullZoneId: "${{ secrets.ZONE_ID }}"
          upload: "true"
          remove: "true"
          purgePullZone: "true"